kind: Deployment
apiVersion: apps/v1
metadata:
  name: login-api
  labels:
    app: login-api
spec:
  replicas: {{.Values.login.deployment.replicas}}
  selector:
    matchLabels:
      app: login-api
  template:
    metadata:
      labels:
        app: login-api
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: login-api-image
          image: {{.Values.login.image.name}}
          env:
            - name: MONGOOSE_CONNECT
              valueFrom:
                secretKeyRef:
                  name: login-api-secret
                  key: mongodburl
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(HOST_IP):4318
            - name: OTEL_SERVICE_NAME
              value: "login_service"
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.login.http.port}}
