apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-api
  template:
    metadata:
      labels:
        app: login-api
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: login-api-image
          image:  aminfelah/login-api-micro-service
          env:
            - name: MONGOOSE_CONNECT
              valueFrom:
                secretKeyRef:
                  name: login-api-secret
                  key: mongodburl
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(HOST_IP):4318
            - name: OTEL_SERVICE_NAME
              value: "login_service"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false