apiVersion: v1
kind: Service
metadata:
  name: music-player-front-service
  labels:
    app: music-player-front
spec:
  selector:
    app: music-player-front
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
